server:
  port: 8084
  error:
    include-message: always
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/ordering_system
    username: postgres
    password: java
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: restordering@gmail.com
    password: cpvjtrznsinntbkq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: randomsecretkey
  lifetime: 30m
logging:
  level:
    root: info
    com:
      ordering_system:
        api:
          OrderingSystemApplication: error
        service:
          impl: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n%throwable"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: src/main/resources/logs.log